name: 'Notify Telegram Action'
description: 'Notify via Telegram!'
author: 'Luca Patera'
inputs:
  footer:
    description: 'Message footer'
    required: false
  message:
    description: 'Override default message'
    required: false
  STATUS:
    description: 'Job status'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'message-square'
  color: 'blue'
