name: CI

on:
  push:

jobs:
  setup-success:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run success
        run: exit 0
  notify-success:
    needs: setup-success
    continue-on-error: true
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Send message to Telegram
        uses: ./
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
        with:
          status: ${{job.status}}
  setup-fail:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run fail
        run: exit 1
  notify-fail:
    needs: setup-fail
    continue-on-error: true
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Send message to Telegram
        uses: ./
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
        with:
          status: ${{job.status}}