name: CI

on:
  push:
  pull_request:
    

jobs:
  success:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run success
        run: exit 0
      - name: Send message to Telegram
        uses: ./
        if: always()
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
          TELEGRAM_TOPIC: ${{ secrets.TELEGRAM_TOPIC }}
        with:
          status: ${{job.status}}
  fail:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run fail
        run: exit 1
      - name: Send message to Telegram
        uses: ./
        if: always()
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
          TELEGRAM_TOPIC: ${{ secrets.TELEGRAM_TOPIC }}
        with:
          status: ${{job.status}}
  no-status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run success
        run: exit 0
      - name: Send message to Telegram
        uses: ./
        if: always()
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
          TELEGRAM_TOPIC: ${{ secrets.TELEGRAM_TOPIC }}
  alternative-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run success
        run: exit 0
      - name: Send message to Telegram
        uses: ./
        if: always()
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
          TELEGRAM_TOPIC: ${{ secrets.TELEGRAM_TOPIC }}
        with:
          commit_template: ./templates/commit-alternative.mustache
          status: ${{job.status}}